#!/bin/sh
echo look for syntax errors or undefined names
python3 -m flake8 --count --select=E9,F63,F7,F82 --show-source --statistics $1
echo look for all errors as warnings
python3 -m flake8 --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics $1
echo run pytest
python3 -m pytest $1
